name: track_project
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.2.5
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - icu=58.2
  - isort=4.3.21
  - jdcal=1.4.1
  - jpeg=9b
  - lazy-object-proxy=1.4.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libglu=9.0.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mccabe=0.6.1
  - ncurses=6.1
  - openpyxl=2.6.2
  - openssl=1.1.1c
  - pango=1.42.4
  - pcre=8.43
  - pip=19.2.2
  - pixman=0.38.0
  - pylint=2.3.1
  - python=3.7.4
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - wheel=0.33.4
  - wrapt=1.11.2
  - wxpython=4.0.4
  - xz=5.2.4
  - zlib=1.2.11

